name: Deploy Kufar

on: 
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Kufar
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/git/kufar
            git pull origin master
            sleep 5 && pkill -f 'kufar.jar'
            ./gradlew build
            ./gradlew copyJar
            nohup java -jar kufar.jar > kufarV.log 2>&1 &